name = "Lighting Controller"

[meta]
date_time = 133647102094141208
game_version = "0.2.5025.22811"
description = "Interior motion actuated lighting controller​"
author = "dm."
workshop_file_handle = "dm."
